services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile

    volumes:
      - ./frontend:/usr/app

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/app
