services:

  mongo:
    image: mongo
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod

    depends_on:
      - nginx

    volumes:
      - frontend_static:/usr/app/build

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_static:/usr/share/nginx/html

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    depends_on:
      - mongo


volumes:
  frontend_static:
