services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    networks:
      - custom-network 
    volumes: 
      - /etc/letsencrypt:/etc/letsenctypt:ro
      - /home/Desktop/ReactGirlySocialNetowk/uploads:/usr/share/nginx/uploads
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 6969:6969
    networks:
      - custom-network
    volumes:
      - ./uploads:/usr/src/uploads

networks:
  custom-network:
    driver: bridge
