services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt/live/rgsn.live:/etc/letsencrypt/live/rgsn.live:ro
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 6969:6969
    depends_on:
      - mongo
